"""Initial migration

Revision ID: 59849200098d
Revises: 
Create Date: 2024-04-11 20:57:22.679645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59849200098d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('Band', sa.Integer(), nullable=True),
    sa.Column('riskTolerance', sa.Integer(), nullable=True),
    sa.Column('stocksPercentage', sa.Float(), nullable=True),
    sa.Column('bondsPercentage', sa.Float(), nullable=True),
    sa.Column('cashPercentage', sa.Float(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('choice')
    op.drop_table('question')
    op.drop_table('profile')
    # ### end Alembic commands ###
